# Remember to type source ~/.bash_profile to reload

. ~/scripts/workflow-config/extract/extract.sh
. ~/scripts/workflow-config/z/z.sh
. ~/scripts/workflow-config/history.sh
. ~/scripts/workflow-config/cl.sh
. ~/scripts/workflow-config/fawk.sh
. ~/scripts/workflow-config/ls.sh

# Git autocompletion
if [ -f `brew --prefix`/etc/bash_completion ]; then
    . `brew --prefix`/etc/bash_completion
else
    echo "Warning - git autocompletion not installed."
fi