# Remember to type source ~/.bash_profile to reload

. ~/scripts/workflow-config/extract/extract.sh
. ~/scripts/workflow-config/z/z.sh
. ~/scripts/workflow-config/history.sh
. ~/scripts/workflow-config/cl.sh
. ~/scripts/workflow-config/fawk.sh
. ~/scripts/workflow-config/ls.sh

# Enable opening sublime from the command line 
ln -s /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl /usr/local/bin/subl